create table if not exists public.creator_portfolios (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.creator_profiles(id) on delete cascade,
  title text not null,
  description text,
  image_url text not null,
  project_url text,
  status text not null default 'draft'::text check (status in ('draft', 'published')),
  display_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.creator_portfolios enable row level security;

create policy "Public can view published portfolios"
  on public.creator_portfolios
  for select
  using (status = 'published');

create policy "Authenticated creator can manage own portfolios"
  on public.creator_portfolios
  to authenticated
  using (creator_id = auth.uid())
  with check (creator_id = auth.uid());

create index if not exists idx_creator_portfolios_creator_id
  on public.creator_portfolios(creator_id);

create index if not exists idx_creator_portfolios_status
  on public.creator_portfolios(status);
